'''Miscellaneous utilities'''
from hashlib import sha256
from uuid import uuid4


def salt_and_hash(plaintext, salt=None):
    '''Salt and hash a plaintext value.'''
    if salt is None:
        salt = sha256(uuid4().bytes).hexdigest()
    return salt + sha256(str.encode(salt + str(plaintext))).hexdigest()


def salt_and_hash_compare(plaintext, value):
    '''Compare a plaintext value with a value generated by salt_and_hash().'''
    # note: the salt is the first 64 characters of the salted and hashed value
    return salt_and_hash(plaintext, value[:64]) == value
